ex1.out: ex1.c ../glad.c
	$(CC) ex1.c ../glad.c ../utils.c -o ex1.out -Wall -Wextra -std=c99 -lGL -lglfw -ldl

ex2.out: ex2.c ../glad.c
	$(CC) ex2.c ../glad.c ../utils.c -o ex2.out -Wall -Wextra -std=c99 -lGL -lglfw -ldl

ex3.out: ex3.c ../glad.c
	$(CC) ex3.c ../glad.c ../utils.c -o ex3.out -Wall -Wextra -std=c99 -lGL -lglfw -ldl
